=== M2TNAH/ProjetXML_Tolkien/XML/template.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT TEI (teiHeader, text)>
<!ATTLIST TEI xmlns CDATA #FIXED "http://www.tei-c.org/ns/1.0">

<!-- TEI Header -->
<!ELEMENT teiHeader (fileDesc, profileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT publicationStmt (p, publisher)>
<!ELEMENT publisher (#PCDATA)>

<!-- Paragraph in the body or header -->
<!ELEMENT p (#PCDATA | persName | geogName | orgName | objectName | q | date | gap )*>
<!ATTLIST p type CDATA #IMPLIED>

<!-- Bibliography -->
<!ELEMENT sourceDesc (bibl)>
<!ELEMENT bibl (title, author, editor+, publisher, pubPlace?, date, biblScope)>
<!ATTLIST bibl type CDATA #REQUIRED xml:lang CDATA #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT editor (#PCDATA)>
<!ATTLIST editor resp CDATA #REQUIRED>

<!-- Additional information on the publisher, place, and date of publication -->
<!ELEMENT pubPlace (#PCDATA)>
<!ELEMENT biblScope (#PCDATA)>
<!ATTLIST biblScope unit CDATA #REQUIRED from CDATA #REQUIRED to CDATA #REQUIRED >

<!-- Date and time elements in the header and in the text body -->
<!ELEMENT date (#PCDATA) >
<!ATTLIST date when CDATA #IMPLIED type CDATA #IMPLIED when-custom CDATA #IMPLIED>

<!-- Character and location identification -->
<!ELEMENT profileDesc (particDesc, settingDesc)>
<!ELEMENT particDesc (listPerson)>
<!ELEMENT listPerson (org*, person*)>
<!-- Characters, name and race -->
<!ELEMENT org (person*) >
<!ATTLIST org type CDATA #REQUIRED xml:id ID #REQUIRED>
<!ELEMENT person EMPTY>
<!ATTLIST person xml:id ID #REQUIRED>
<!-- Locations -->
<!ELEMENT settingDesc (listPlace)>
<!ELEMENT listPlace (place+)>
<!ELEMENT place EMPTY>
<!ATTLIST place xml:id ID #REQUIRED type CDATA #REQUIRED>

<!-- TEXT BODY -->
<!ELEMENT text (body)>
<!ELEMENT body (div+)>

<!-- Division in the text, here used for chapters -->
<!ELEMENT div (head?, p+)>
<!ATTLIST div type CDATA #IMPLIED n CDATA #IMPLIED>

<!-- Chapter -->
<!ELEMENT head (#PCDATA)>

<!-- Indication of skipped passages with the number of skipped lines -->
<!ELEMENT gap EMPTY>
<!ATTLIST gap reason CDATA #IMPLIED quantity CDATA #IMPLIED>

<!-- Names of characters, races, locations, and cited mythological objects -->
<!ELEMENT persName (#PCDATA)>
<!ATTLIST persName ref IDREF #IMPLIED>
<!ELEMENT geogName (#PCDATA)>
<!ATTLIST geogName ref IDREF #IMPLIED>
<!ELEMENT orgName (#PCDATA)>
<!ATTLIST orgName ref IDREF #IMPLIED>
<!ELEMENT objectName (#PCDATA)>
<!ATTLIST objectName ref IDREF #REQUIRED>

<!-- Dialogues with indication of the speaker (who) and the addressee (toWhom) -->
<!ELEMENT q (#PCDATA | persName | geogName | orgName | objectName | p | date | gap)*>
<!ATTLIST q who IDREF #REQUIRED toWhom IDREF #IMPLIED >

=== M2TNAH/ProjetXML_Tolkien/XML/example.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TEI SYSTEM "template.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
   <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>File Title</title>
         </titleStmt>
         <publicationStmt>
            <p>License</p>
            <publisher>MaÃ«lys Gioan</publisher>
         </publicationStmt>
         <sourceDesc>
            <bibl type="book" xml:lang="fr">
               <title>Book Title</title>
               <author>Book Author</author>
               <editor resp="translator">Translator</editor>
               <editor resp="translator">Other Translator</editor>
               <publisher>Publisher</publisher>
               <pubPlace>Place of Publication</pubPlace>
               <date when="1993" type="publication">a date</date>
               <biblScope unit="page" from="30" to="31">page numbers</biblScope>
            </bibl>
         </sourceDesc>
      </fileDesc>
      <profileDesc>
         <particDesc>
            <listPerson>
               <org type="race" xml:id="orgID_1">
                  <person xml:id="persID_1"/>
                  <person xml:id="persID_2"/>
               </org>
               <org type="race" xml:id="orgID_2"/>
            </listPerson>
         </particDesc>
         <settingDesc>
            <listPlace>
               <place xml:id="placeID_1" type="region"/>
               <place xml:id="placeID_2" type="river"/>
               <place xml:id="placeID_3" type="tree"/>
            </listPlace>
         </settingDesc>
      </profileDesc>
   </teiHeader>
   
   <text>
      <body>
         <div type="chapter" n="1">
            <head>Chapter Title of the Excerpt.</head>
            <p> 
               A paragraph of text
               <gap reason="sampling" quantity="3l"/>
               <orgName ref="orgID_1">group Name 1</orgName>
               <orgName ref="orgID_2">group Name 2</orgName>
               <persName ref="persID_1">character Name</persName>
               <persName ref="persID_2">second Character</persName>
               <geogName ref="placeID_1">region Name</geogName>
               <geogName ref="placeID_2">river Name</geogName>
               <geogName ref="placeID_3">place Name</geogName>
               <objectName ref="placeID_3">object Name</objectName>
               <date when="NNNNN" type="year">a date</date>
               <date when="NNNNN" type="year">a date</date>
               <date when-custom="nomEpoque" type="era">the name of an era</date>
               <!-- The <q> tag can contain the same elements as the <p> tag -->
               <q who="persID_1" toWhom="persID_2">a dialogue</q>
            </p>
            <p>
               Second paragraph of text.
            </p>
         </div>
      </body>
   </text>
</TEI>
